export const defaultGlobalStyles = {
    "palette": {
        primary: ['bg-white dark:bg-black'],
        secondary: ['bg-zinc-100 dark:bg-zinc-900'],
        accent1: ['bg-white'],
        accent2: ['bg-blue-300'],
        accent3: ['bg-blue-100'],
    },
    "borderColor": {
        borderRadius: ['rounded-lg'],
        borderColor: ['border-zinc-200 dark:border-zinc-700'],
    },
    "text": {
        textBody: ['text-black'],
        textAccent: ['text-zinc-800'],
        textMuted: ['text-zinc-200'],
        placeholder: ['placeholder-zinc-600 dark:placeholder-zinc-400'],
    },
    "states": {
        focused: ['focus-visible:outline-none focus-visible:ring-blue-400 focus-visible:ring focus-visible:border-0 transition-colors'],
        disabled: ['disabled:cursor-not-allowed disabled:opacity-50'],
        error: ['border-red-400 dark:border-red-400 bg-red-200/20 dark:bg-red-300/20 text-red-400'],
    },
    "indicators": {
        errorColor: ['bg-red-500'],
        successColor: ['bg-green-500'],
        warningColor: ['bg-yellow-500'],
        errorText: ['text-red-500'],
    }
}

export const defaultStyles = {
    "div": {
        "borderColor": ["border border-zinc-300 dark:border-zinc-600"],
        "container": ["flex"],
    },
    "divDivider": {
        "container": ["w-full h-px"],
        "base": [""],
    },
    "divLayoutContainer": {
        "bgColor": ["bg-white dark:bg-black"],
        "borderRadius": ["rounded-lg"],
        "shadow": ["shadow-md"],
        "container": ["p-4"],
        "base": [""],
    },
    "input": {
        "focus": ["focus-visible:outline-none focus-visible:ring-blue-400 focus-visible:ring focus-visible:border-0 transition-colors"],
        "disabled": ["disabled:cursor-not-allowed disabled:opacity-50"],
        "invalid": ["invalid:border-pink-500 invalid:text-pink-600 focus:invalid:border-pink-500 focus:invalid:ring-pink-500"],
        "container": ["flex justify-center items-center p-2 transition-colors"],
    },
    "inputDefault": {
        "bgColor": ['bg-white dark:bg-black'],
        "textSize": ['text-sm'],
        "textColor": ['text-black dark:text-white'],
        "placeholder": ['placeholder-zinc-600 dark:placeholder-zinc-400'],
        "dimensions": ["h-9 w-full"],
        "shadow": ["shadow-sm"],
        "borderColor": ["border border-zinc-300 dark:border-zinc-700"],
        "borderRadius": ["rounded"],
        "base": [""],
    },
    "text":{
        "spacing": [''],
    },
    "text1": {
        "textSize": ["text-5xl"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-extrabold"],
        "base": [""],
    },
    "text2": {
        "textSize": ["text-3xl"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-semibold"],
        "base": [""],
    },
    "text3": {
        "textSize": ["text-2xl"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-semibold"],
        "base": [""],
    },
    "text4": {
        "textSize": ["text-lg"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-semibold"],
        "base": [""],
    },
    "text5": {
        "textSize": ["text-sm"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-semibold"],
        "base": [""],
    },
    "text6": {
        "textSize": ["text-xs"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-normal"],
        "base": [""],
    },
    "textLabel": {
        "textSize": ["text-xs"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-semibold"],
        "base": [""],
    },
    "textBody": {
        "textSize": ["text-sm"],
        "textColor": ["text-black dark:text-white"],
        "font": ["font-normal"],
        "base": [""],
    },
    "textMuted": {
        "textSize": ["text-sm"],
        "textColor": ["text-zinc-600 dark:text-zinc-400"],
        "font": ["font-normal"],
        "base": [""],
    },
    "textAccent": {
        "textSize": ["text-sm"],
        "textColor": ["text-blue-400"],
        "font": ["font-normal"],
        "base": [""],
    },
    "textQuote": {
        "textSize": ["text-sm"],
        "textColor": ["text-zinc-600 dark:text-zinc-400"],
        "font": ["italic"],
        "base": [""],
    },

    "card": {
        "hover": [""],
    },
    "cardDefault": {
        "bgColor": ["bg-white dark:bg-zinc-900"],
        "borderColor": ["border border-zinc-300 dark:border-zinc-600"],
        "borderRadius": ["rounded"],
        "shadow": ["shadow-md hover:shadow-lg"],
        "container": ["p-4 transition-all duration-200 ease-in-out"],
        "base": [""],
    },
    "cardUtil": {
        "bgColor": ["bg-white dark:bg-zinc-900"],
        "borderColor": ["border border-zinc-200 dark:border-zinc-700"],
        "borderRadius": ["rounded"],
        "container": ["p-1 transition-all transform"],
        "base": [""],
    },
    "btn": {
        "focus": ["focus-visible:outline-none focus-visible:ring-blue-400 focus-visible:ring focus-visible:border-0 transition-colors"],
        "disabled": ["disabled:cursor-not-allowed disabled:opacity-50"],
        "container": ["flex justify-center items-center px-2 h-9 duration-200"],
    },
    "btnPrimary": {
        "bgColor": ["bg-zinc-900 dark:bg-white"],
        "hoverbgColor": ["hover:bg-zinc-700 dark:hover:bg-zinc-300"],
        "textColor": ["text-white dark:text-black"],
        "textSize": ["text-sm"],
        "borderColor": ["border border-zinc-500 dark:border-zinc-300"],
        "borderRadius": ["rounded-md"],
        "base": [""],
    },
    "btnOutline": {
        "hoverbgColor": ["hover:bg-zinc-200 dark:hover:bg-zinc-800"],
        "textSize": ["text-sm"],
        "textColor": ["text-black dark:text-white"],
        "borderColor": ["border-zinc-600 dark:border-zinc-300"],
        "borderWeight": ["border-2"],
        "borderRadius": ["rounded"],
        "base": [""],
    },
    "btnSecondary": {
        "bgColor": ["bg-zinc-100 dark:bg-zinc-700"],
        "hoverbgColor": ["hover:bg-zinc-200 dark:hover:bg-zinc-800"],
        "textSize": ["text-sm"],
        "textColor": ["text-black dark:text-white"],
        "borderColor": ["border border-zinc-300 dark:border-zinc-600"],
        "borderRadius": ["rounded"],
        "base": [""],
    },
    "icon": {
        "focus": [""],
        "disabled": ["disabled:cursor-not-allowed disabled:opacity-50"],
        "container": ["flex justify-center items-center px-2 h-8 w-8 duration-200"],
    },
    "iconSmall": {
        "bgColor": ["bg-zinc-100 dark:bg-zinc-700"],
        "hoverbgColor": ["hover:bg-zinc-200 dark:hover:bg-zinc-800"],
        "textSize": ["text-xs"],
        "textColor": ["text-black dark:text-white"],
        "borderColor": ["border border-zinc-300 dark:border-zinc-600"],
        "borderRadius": ["rounded"],
        "base": [""],
    },
    "badge": {
        "disabled": ["disabled:cursor-not-allowed disabled:opacity-50"],
        "container": ["flex justify-center items-center p-1 px-2 duration-200"],
    },
    "badgeDefault": {
        "bgColor": ["bg-black dark:bg-white"],
        "hoverbgColor": ["hover:bg-zinc-800 dark:hover:bg-zinc-300"],
        "textSize": ["text-xs"],
        "textColor": ["text-white dark:text-black"],
        "borderRadius": ["rounded-full"],
        "base": [""],
    },
}